theme: jekyll-theme-minimal
title: Quart[0\x]una
description: A blog about my IT journey

domain: quartoxuna.github.io
url: http://quartoxuna.github.io

category_order:
  - homelab
  - misc

remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
